[package]
name = "end_credits"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"

[profile.dev]
opt-level = 1

# Apply all optimiations to dependencies in dev builds
[profile.dev.package."*"]
opt-level = 3